### ISSUE TITLE
ITK ERROR: Object factory failed to instantiate N3itk23Forward1DFFTImageFilterINS_39CurvilinearArraySpecialCoordinatesImageIfLj2EEENS1_INSt3__17complexIfEELj2EEEEE

### ISSUE THREAD

**Issue by Nicola17** [KitwareMedical/ITKUltrasound#183] opened 2022-03-09 17:10 UTC
Hey there,
I'm rather new to the project but it looks really cool!

I'm trying to reproduce this example: https://github.com/KitwareMedical/ITKUltrasound/blob/master/examples/TimeGainCompensation.ipynb

but I get the following error:
`ITK ERROR: Object factory failed to instantiate N3itk23Forward1DFFTImageFilterINS_39CurvilinearArraySpecialCoordinatesImageIfLj2EEENS1_INSt3__17complexIfEELj2EEEEE`

Note that I have the same issue on my Mac, on a Ubuntu container and a SciLinux distro.

Any guidance?

**Comment by tbirdso** [comment] 2022-03-09 19:25
Hi @Nicola17 , thank you for trying out ITKUltrasound!

The error that you described are present in itk-ultrasound v0.5.1 and v0.5.2 and are tracked in #172. A fix is pending in #182, but will not be available in pip-installable packages until after updated [ITK](https://github.com/insightsoftwareconsortium/itk) v5.3rc04 Python packages are released.

In order to try out all examples, for the moment I would recommend downgrading to itk-ultrasound v0.5.0, which depends on the ITK v5.2.1 stable release.
```
python -m pip install itk==v5.2.1.post1 itk-ultrasound==v0.5.0
```

Note that this will not include the most recent additions to ITKUltrasound such as `itk.AttenuationImageFilter`. If you are interested in accessing those additions it is possible to build the ITKUltrasound Python packages locally on your machine. You can find more information about building external modules in the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) or on the [ITK Discourse discussion board](https://discourse.itk.org/).

For tracking purposes I am going to close this issue as a duplicate of #172 for now. However, please feel free to reopen if you experience any issues downgrading or other problems with running example notebooks.

(Pinging @dzenanz for visibility.)

**Closed by tbirdso** 2022-03-09 19:25 UTC

**Comment by Nicola17** [comment] 2022-03-09 20:42
@tbirdso - it worked! thanks a lot!

Maybe a question that is related to this. Say that I want to do a scan conversion (i.e. going from a grid to the traditional US shape). Is there a snippet that can help me with this?

**Comment by tbirdso** [comment] 2022-03-09 21:07
@Nicola17 I'm glad to hear that it worked! Unfortunately I don't believe we have an example for working with `itk.CurvilinearArraySpecialCoordinateImage`s (the traditional sweep shape). Perhaps @dzenanz has a code snippet for conversion?

You may be able to read in your grid-based image directly into curvilinear format with `itk.ImageFileReader`:
```py
>>> import itk
>>> image_type = itk.CurvilinearArraySpecialCoordinatesImage[itk.F,2]
>>> reader = itk.ImageFileReader[image_type].New()
>>> reader.SetFileName('path/to/image')
>>> reader.Update()
>>> image = reader.GetOutput()
```

If you are working with an image already loaded in memory then [`itk.ResampleImageFilter`](https://itk.org/Doxygen/html/classitk_1_1ResampleImageFilter.html) may provide what you need.
